# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.15
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: anupaxtream@gmail.com
author_name: acez0z
cloud_provider: none
contract_name: Moderator
preset_name: production
project_name: DML

